"""Run every measurement and write RESULTS.md.

`python measure/run_all.py`          regenerate RESULTS.md
`python measure/run_all.py --check`  fail if RESULTS.md is out of date

The papers quote RESULTS.md and nothing else. If a number appears in a paper
and not here, it is either an arithmetic identity or a literature value, and it
is marked as such at the point of use.
"""

import io
import subprocess
import sys
from contextlib import redirect_stdout
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "RESULTS.md"

SCRIPTS = [
    ("counting.py", "How big is the space of positions",
     "Each row adds one constraint to the row above. The `saved` column is the\n"
     "cost of that constraint in bits, and is the only column worth reading."),
    ("symmetry.py", "What symmetry survives, and what it is worth",
     "`bits saved` is log2 of the mean orbit size: the most a canonical form\n"
     "could ever save. `ceiling` is log2 of the group order, which it reaches\n"
     "only when the group acts freely and the family is closed under it."),
    ("plyrate.py", "Bits per ply",
     "Costs that depend only on the number of legal moves, not on which ones."),
    ("envelope.py", "How much of a stored game is chess",
     "The move stream compresses; the keys and signatures around it do not.\n"
     "This is the table that decides how much compression is worth buying."),
]

HEADER = """<!-- generated by measure/run_all.py -- do not edit by hand -->
# Measured results

Every number quoted in `papers/` that is not an arithmetic identity or an
explicitly cited literature value is produced by one of these scripts.
Regenerate with `python measure/run_all.py`.
"""


def render() -> str:
    parts = [HEADER]
    for script, title, note in SCRIPTS:
        buf = io.StringIO()
        code = compile((HERE / script).read_text(), script, "exec")
        g = {"__name__": "__main__", "__file__": str(HERE / script)}
        sys.path.insert(0, str(HERE))
        try:
            with redirect_stdout(buf):
                exec(code, g)
        finally:
            sys.path.pop(0)
        parts.append(f"\n## {title}\n\n`measure/{script}`\n\n{note}\n\n"
                     f"```\n{buf.getvalue().rstrip()}\n```\n")
    return "".join(parts)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print("RESULTS.md is stale; run `python measure/run_all.py`",
                  file=sys.stderr)
            sys.exit(1)
        print("RESULTS.md is current")
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(HERE.parent)}")
