#!/usr/bin/env python3
"""Lift the chess engine and field maths out of index.html into an ES module,
so the test suite runs against exactly the code the page ships."""
import sys, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "index.html").read_text()
def between(a, b):
    i = src.index(a); j = src.index(b)
    return src[i:j]
parts = [
    between("// ==ENGINE-START==", "// ==ENGINE-END=="),
    between("const VAL={p:100", "/* ================= EVALUATION"),
]
exports = ("export {parseFEN,toFEN,clone,legalMoves,pseudo,make,unmake,inCheck,sanOf,"
           "parsePGN,perft,attackedBy,kingSq,START,IDX,ALG,SQ,F,R,"
           "VAL,SEEV,attackerList,riskAt,fields,smooth,sample,contour,segLen};\n")
out = root / "tools" / "tests" / "engine.mjs"
out.write_text("// GENERATED by tools/extract-engine.py — do not edit.\n"
               + "\n".join(parts) + "\n" + exports)
print("wrote", out.relative_to(root))
